# Generated by Django 3.2.13 on 2022-07-27 02:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.CharField(default='', max_length=50, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人签名'),
        ),
    ]
