# Generated by Django 3.2.13 on 2022-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220727_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avator',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avtor'),
        ),
    ]
