# Generated by Django 2.2.12 on 2022-05-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20220529_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='prince',
            new_name='price',
        ),
    ]
