# Generated by Django 2.2.12 on 2022-06-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='tiltle',
            new_name='title',
        ),
    ]
